# Generated by Django 3.2.8 on 2024-09-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_createtask_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createtask',
            options={'ordering': ['-date']},
        ),
    ]
