# Generated by Django 3.2.8 on 2024-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_createtask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
