# Generated by Django 3.2.8 on 2024-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_createtask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
